Cargo.toml
examples/server.rs
examples/sqlite.rs
src/messages/data.rs
src/messages/mod.rs

This patch attempts to use sqlite database as backend and talks postgresql protocol.

Sqlite backend example

---

examples/sqlite.rs
src/api/auth/cleartext.rs
src/api/query.rs
src/api/results.rs
src/error.rs
src/messages/mod.rs
src/messages/response.rs
src/tokio.rs

- Provide api for postgresql error/notice messages
- Refining `PgWireError` to make it user-friendly for our api users.

Refining error API and messages

---

Cargo.toml
examples/gluesql.rs

This example implements a postgresql protocol support for [gluesql engine](https://github.com/gluesql/gluesql).

Add example for gluesql

---

src/tokio.rs

Run the following command:
```console
cargo run --example server
```
Then executes `nc` command in another terminal console:
```console
nc 127.0.0.1 5432 -w 1 ; nc 127.0.0.1 5432 -w 1
psql -h 127.0.0.1 -p 5432
```
The connection will block for a very long time(but still can be connected).
The reason is `tcp_socket.peek()` always returns 0 even if the peer is closed and the main process login will be blocked in `peek_for_sslrequest()`. 
It is reasonable to read the data from the socket buffer although the peer is closed(maybe the data is still in recv buffer). But in the psql protocol scenario, I think the socket should always rw.

fix: add tcp socket readable guard

---

src/tokio.rs

https://man7.org/linux/man-pages/man2/recv.2.html#RETURN_VALUE
> When a stream socket peer has performed an orderly shutdown, the return value will be 0 (the traditional "end-of-file" return).
However,
> The value 0 may also be returned if the requested number of bytes to receive from a stream socket was 0.

fix: simply treat zero peek size as dead tcp stream

---

Cargo.toml
src/api/auth/scram.rs

feat: use ring for digest and signature

---

Cargo.toml
README.md
examples/datafusion.rs

Fixes #55 
This patch adds an example to expose datafusion query engine with pgwire.

Add datafusion example

---

examples/scram.rs
examples/sqlite.rs
src/api/auth/mod.rs
src/api/auth/noop.rs
src/api/query.rs
tests-integration/test-server/src/main.rs

Update API for our default parameter provider implementation and make it modifiable. So user won't have to define their own to override some defaults.

feat: improve server parameter apis

---

examples/datafusion.rs
examples/gluesql.rs
examples/scram.rs
examples/secure_server.rs
examples/server.rs
examples/sqlite.rs
src/api/query.rs
src/api/results.rs
tests-integration/test-server/src/main.rs

This patch updates tag API with new constructors and oid support.

refactor: update tag api

---

src/api/results.rs
src/types/mod.rs
tests-integration/test-server/src/main.rs

Fixes https://github.com/sunng87/datafusion-postgres/issues/5

fix: show text NULL for null

---

Cargo.toml
src/types/mod.rs

fix: string escape for array

---

src/api/query.rs
src/tokio/server.rs

`Flush` is part of https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY

add flush to ExtendedQueryHandler

---

src/types/mod.rs
tests-integration/test-server/src/main.rs

fix: text encoding for bytea

---

src/api/auth/mod.rs

Fixes #232 
Use a postgres compatible version as defaults

feat(API): Upgrade server version format for compatibility improvement.

---

src/api/query.rs

feat: add ClientPortalStore for simple query client

---

.github/workflows/ci.yml
Cargo.toml
examples/client.rs
examples/server.rs
src/api/client/auth.rs
src/api/client/config.rs
src/api/client/mod.rs
src/error.rs
src/lib.rs
src/tokio/client.rs

This patch refactored and implementation client APIs for startup and authentication.

feat: authentication for client apis

---

README.md
examples/client.rs
src/api/client/auth.rs
src/api/client/mod.rs
src/api/client/query.rs
src/api/results.rs
src/error.rs
src/tokio/client.rs

This patch implements simple query protocol for client api

feat: client simple query implementation

---

src/messages/codec.rs

When an empty buffer is passed to get_cstring, the function panics when
it attempts to skip '\0'. Handle empty buffers separately and return
None.

codec: do not panic on empty buffer in get_string

---

examples/duckdb.rs

The existing DuckDB example tries to generate the header before querying the statement.
It seems that this is [not supported](https://github.com/duckdb/duckdb-rs/issues/376) and leads to a server [panic](https://github.com/duckdb/duckdb-rs/issues/261).
With a little change, we can generate the header after the statement is queried.

fix: generate header after query in DuckDB example

---

README.md
src/api/auth/cleartext.rs
src/api/auth/md5pass.rs
src/api/auth/mod.rs
src/api/auth/noop.rs
src/api/auth/scram.rs
src/error.rs
src/messages/mod.rs
src/messages/startup.rs

feat: protocol negotiation

---

flake.nix
src/error.rs
src/messages/cancel.rs
src/messages/startup.rs

Validate secretkey length before encoding and decoding.

feat: validate secretkey
