sunng87/pgwire

src/api/portal.rs
src/api/results.rs
src/messages/data.rs
src/messages/extendedquery.rs
src/messages/mod.rs

This patch replaces `Vec<u8>` with `Bytes` for less allocation and data copy.

Using bytes for Bind parameters and DataRow data

---

examples/server.rs
examples/sqlite.rs
src/api/auth/cleartext.rs
src/api/auth/mod.rs
src/api/auth/noop.rs
src/api/mod.rs
src/api/query.rs
src/tokio.rs

Addresses #5 
The previous implementation of auth framework is limited by rust's type system. So we have to change the design by providing a concrete type `CleartextPasswordAuthStartupHandler` and use a smaller `PasswordVerifier` as an extending point.
We still need to figure out a way to deal with how to customize `server_parameters`

Refactor startup and auth modules

---

examples/server.rs
examples/sqlite.rs
src/tokio.rs

Fixes #8 
This patch moves `tokio::spawn` out of `process_socket` so that users could use their own runtime to spawn.
It also dropped `socket_addr` as input because the information is carried by `TcpStream` already.

Refining Tokio API

---

examples/server.rs
examples/sqlite.rs
src/api/results.rs

Fixes #10 
This patch brings in API support for text format response, which is required for simple_query mode in postgresql.

API support for text response

---

examples/server.rs
examples/sqlite.rs
src/api/query.rs
src/messages/mod.rs
src/messages/response.rs

Fixes #9 
As defined in https://www.postgresql.org/docs/8.2/protocol-flow.html#AEN67013, a simple query string can contains multiple queries so here we use `Vec<Response>` to represent the result for a simple query.

feat: allow multiple queries in simple query

---

src/api/query.rs
src/api/results.rs
src/tokio.rs

This is the first part of #17 implementation.
This patch refactors `QueryResponse` to use async stream instead of original implementation, which buffers all `DataRow`s in memory.

Stream response

---

Cargo.toml
examples/sqlite.rs
src/api/auth/md5pass.rs
src/api/auth/mod.rs
src/api/mod.rs

This patch introduces support for postgresql's md5 hash password authentication method.
It also refined our password verifier to provide more context for authentication, including:
- username
- database
- host

Md5 password support, and new PasswordVerifier API

---

src/messages/extendedquery.rs
src/messages/mod.rs

The PostgreSQL wire protocol has a Flush front-end message to force the server to send out responses before the final Sync. Add the message definition so library users can use it.

Add Flush front-end message

---

Cargo.toml
examples/scram.rs
src/api/auth/scram.rs
src/error.rs

This patch implements `SCRAM-SHA256-PLUS` with `tls-server-end-point` channel binding. It uses server certificate for channel binding. TLS is required when using `SCRAM-SHA256-PLUS`

SCRAM-SHA256-PLUS with tls-server-end-point channel binding

---

examples/gluesql.rs
examples/scram.rs
examples/secure_server.rs
examples/server.rs
examples/sqlite.rs
src/api/mod.rs
src/api/portal.rs
src/api/query.rs
src/api/results.rs
src/api/stmt.rs
src/api/store.rs
src/messages/extendedquery.rs
src/tokio.rs

This patch resigned our `ExtendedQueryHandler` with following updates:
- Assume all `ExtendedQueryHandler`s are stateful (a handler for each connection)
- Move cached statements and portals to `PortalStore`, and `PortalStore` is associated with `ExtendedQueryHandler` instead of `ClientInfo`.
- Abstract `QueryParser` trait for `parse` step. `Portal` and `StoredStatement` now stores parsed statement instead of raw query string
See `sqlite` example for its usage.

Stateful extended query apis

---

examples/gluesql.rs
examples/scram.rs
examples/secure_server.rs
examples/server.rs
examples/sqlite.rs
src/api/portal.rs
src/api/query.rs
src/api/results.rs
src/error.rs

This patch updates query apis to deal with `Describe` and `Execute` separately. Now it's possible to return `RowDescription` without actually executing the query. `Describe` on prepared statement is also supported.
Fixes #40 
Fixes #29 
As our `ExtendedQueryHandler` is getting bigger, we provide a placeholder implementation for those doesn't implement it in their application.

Add do_describe to ExtendedQueryHandler

---

examples/scram.rs
examples/sqlite.rs
src/api/auth/cleartext.rs
src/api/auth/md5pass.rs
src/api/auth/mod.rs
src/api/auth/scram.rs
src/messages/mod.rs
src/messages/startup.rs

This patch adds a unified `AuthSource` API for developer to implement their user systems. Password (plain or salted) and an optional salt is returned. This design fits both cases that passwords are stored plain or salted (together with salt).

Unifying AuthSource APIs for various authentication mechanism

---

examples/sqlite.rs
src/api/portal.rs
src/api/query.rs
src/api/stmt.rs

As in integration we realize some query engines require parameter types to be able to describe a statement. This patch:
- opens parameter types to `QueryParser`
- reduce data cloned from `StoredStatement` to `Portal`
As always, this is a break change.

feat: improve describe and parser API

---

CHANGELOG.md
src/api/query.rs
src/messages/data.rs
src/messages/mod.rs

This patch fixes:
- parse and bind response is now returned
- respond statement describe request with parameter description, and ready for query

fix: support for describing statement

---

examples/gluesql.rs
examples/secure_server.rs
examples/server.rs
examples/sqlite.rs
src/api/results.rs

This patch merges APIs of  our `TextDataRowEncoder` and `BinaryDataRowEncoder` into `DataRowEncoder`, and allows a row of data to be encoded in different format, as postgres allows.
Developers are required to set field format in `FieldInfo` now.

Refactor DataRowEncoder apis

---

src/messages/mod.rs
src/messages/startup.rs

refactor: include all subtypes in PasswordMessageFamily

---

examples/gluesql.rs
examples/scram.rs
examples/secure_server.rs
examples/server.rs
examples/sqlite.rs
src/tokio.rs

Accepting `MakeHandler` in `process_socket` stops us from reusing data between auth and query handlers.

feat: do not accept MakeHandler in process_socket

---

examples/sqlite.rs
src/api/query.rs
src/api/stmt.rs

Fixes #52 
This patch provides api for parameter type inference, which is a feature provided by postgresql and used by some of clients like rust-postgres.

feat: add DescribeResponse for both parameter and result types

---

CHANGELOG.md
examples/gluesql.rs
examples/scram.rs
examples/secure_server.rs
examples/server.rs
examples/sqlite.rs
src/api/portal.rs
src/api/query.rs
src/api/results.rs

This patch includes changes:
- updated resultset `Response::QueryResponse` lifetime from `'static` to portal or query string, this allows reference of `portal` in streasm
- updated resultset column format access for `portal`

refactor: update resultset stream lifetime to allow usage of portal data

---

Cargo.toml
examples/gluesql.rs
examples/secure_server.rs
examples/server.rs
examples/sqlite.rs
src/api/portal.rs
src/api/results.rs
src/lib.rs
src/types/mod.rs
tests-integration/nodejs/index.js
tests-integration/test-server/Cargo.lock
tests-integration/test-server/src/main.rs

Fixes #56 
This patch adds trait `ToSqlText` in addition to `postgres-types`'s `ToSql`, in order to standardize our text encoding.

feat: ToSqlText for text encoding

---

.github/workflows/ci.yml
Cargo.toml

Reverts sunng87/pgwire#63
We will update x509-certificate later when syn 2.0 get wider adoption

Revert "chore(deps): update x509-certificate requirement from 0.18 to 0.19"

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
examples/datafusion.rs
examples/gluesql.rs
examples/secure_server.rs
examples/server.rs
examples/sqlite.rs
src/api/query.rs
src/api/results.rs
tests-integration/test-server/Cargo.lock
tests-integration/test-server/src/main.rs

Use schema of columns for DataRowEncoder so we can simplify `encode_value` function. Redundant information like type and format are already included in `FieldInfo`s .

refactor: use provided row schema for DataRowEncoder

---

src/api/query.rs

This change fixes issue when connecting pgwire based server as a postgresql data source in grafana.
It sends `;` and awaits for an `EmptyQueryResponse` packet.

fix: treat `;` as empty query

---

CHANGELOG.md
src/api/query.rs
src/api/results.rs
src/messages/data.rs
src/messages/mod.rs

This patch further enhanced what we have in #75.
- It adds `NoData` message in our codec
- It adds `EmptyQuery` in `Response` when implementation detects query is empty
- Sents `NoData` on describe

feat: empty query support for extended query

---

src/api/query.rs
src/api/results.rs

Fixes #82 
This patch provides owned getters for `QueryResponse`.

refactor: add owned version of data_row getters for query response

---

src/api/query.rs

This patch corrects how we respond `ReadyForQuery`. The behaviour is now simplified and corrected: `ReadyForQuery` is only sent when `Sync` packet received.

fix: correct how we handle ready_for_query and sync

---

README.md
src/messages/copy.rs
src/messages/mod.rs

This patch adds codec for copy messages:
- CopyData
- CopyDone
- CopyFail
- Copy[In|Out|Both]Response

feat: Copy messages

---

src/api/query.rs
src/api/stmt.rs

This patch makes `QueryParser` in extended subprotocol handler async. We find in some implementation, it is possible to have an async implementation to parse sql into certain execution plan.

refactor: make QueryParser async

---

.github/workflows/ci.yml
Cargo.toml
examples/sqlite.rs
src/api/portal.rs
src/error.rs

This breaking changes update portal api for getting parameter value. It now requires postgre type for parsing the parameter. Previously we relies on client specified type in `Parse` message. However, postgres allows server to inference the type so that client is not required to provide them. 
This patch allow you to provide server inferenced type as argument to this function.

feat!: allow server inferenced type for portal

---

src/messages/mod.rs

I'm currently working on extended query protocol, but every time I get a Flush message, decode returns an error.
It looks like someone forgot to cover `MESSAGE_TYPE_BYTE_FLUSH` in `PgWireFrontendMessage::decode`, and this patch fixes that.

fix: flush byte is not covered in decode

---

src/error.rs
src/messages/startup.rs

Fixes #111 
This patch attempts to fix panic as described in #111 . It adds additional checks to ensure that the packet length field from startup message is valid (larger than 8). This should prevent panic on invalid clients.

fix: attempt to fix panic on decoding startup message

---

src/messages/mod.rs

Hi!
This patch adds SSLRequest to frontend messages.

fix: there is no SSLRequest in frontend messages

---

src/messages/mod.rs
src/messages/response.rs
src/tokio.rs

Hello again! I'd like to introduce a new backend message.
The backend should communicate with the frontend using backend messages. But this simple concept is broken when you want to response to SslRequest messsage. There is no such message as SslResponse in postgres, so to answer to SslRequest they use a very special approach: the backend sends a single byte containing 'S' or 'N', indicating that it is willing or unwilling to perform SSL, respectively.
I don't like how this is done in postgres and, as for me, it is very unnatural, so this patch introduces SslResponse message, that simply wraps this single byte and provides the backend with convenient API for responding to an SslRequest message.
Also it is better in terms of symmetry: there is SslRequest in frontend messages, but there is …

feat: add SslResponse message

---

src/api/query.rs

If send a lot of data to client, send is far more slow than feed.
It' s a small fix, I tested it.

use feed instread of send

---

examples/bench.rs
examples/datafusion.rs
examples/gluesql.rs
examples/scram.rs
examples/secure_server.rs
examples/server.rs
examples/sqlite.rs
src/api/query.rs
tests-integration/test-server/src/main.rs

Addressing #132 
Previously we removed `Sink` mark from high level API of query handlers (`do_query`/`do_describe`). To be able to send custom messages, we are adding this feature back.

feat: allow sending custom message from high level handler api

---

examples/sqlite.rs
src/api/mod.rs
src/api/query.rs
src/tokio.rs
tests-integration/test-server/src/main.rs

Another approach for fixing the same issue with #139 .
This patch moves `PortalStore` to the client type of `ExtendedQueryHandler`

refactor: move portal store to client

---

Cargo.toml
examples/sqlite.rs
src/api/auth/cleartext.rs
src/api/auth/md5pass.rs
src/api/auth/mod.rs
src/api/auth/scram.rs
src/api/mod.rs
src/api/portal.rs
src/api/query.rs
src/api/results.rs
src/api/stmt.rs
src/api/store.rs
src/error.rs
src/lib.rs
src/messages/copy.rs
src/messages/data.rs
src/messages/extendedquery.rs
src/messages/mod.rs
src/messages/response.rs
src/messages/simplequery.rs
src/messages/startup.rs
src/tokio.rs
tests-integration/test-server/src/main.rs

getset & its proc-macro-error dependencies seem unmaintained (https://github.com/jbaublitz/getset/pull/84#issuecomment-1087770476 https://github.com/jbaublitz/getset/pull/87#issuecomment-1167658416)
In particular, I'm not confident I can get upstream to update to syn 2
I also don't think getter/setter patterns make particular sense in Rust
Use `#[non_exhausitive]` in places to maintain capability to add fields without breaking semver
In some places I omitted `#[non_exhaustive]` where I didn't think it should be necessary, if you disagree let me know & I'll apply it more widely. Similarly, just let me know if you don't think `#[non_exhaustive]` is necessary
In some cases only getters were implemented, in those cases I implemented getter methods by hand & left the fields non-public

Remove getset

---

src/api/mod.rs
src/messages/mod.rs
src/tokio.rs

- the server needs to wait for Sync message from the frontend
before it sends ready for query message back to frontend
- read and discard messages until a Sync is received

dont send ReadyForQuery after error response

---

src/messages/mod.rs
src/tokio.rs

This patch fixes an issue that simple query (psql) client blocks on error as it waits for the `ReadyForQuery` command.

fix: send ReadyForQuery on error when using simple query subprotocol

---

src/tokio.rs

```rust
#[stable(feature = "rust1", since = "1.0.0")]
unsafe impl<T: ?Sized + Sync + Send, A: Allocator + Send> Send for Arc<T, A> {}
#[stable(feature = "rust1", since = "1.0.0")]
unsafe impl<T: ?Sized + Sync + Send, A: Allocator + Sync> Sync for Arc<T, A> {}
```
Release unnecessary bound.
cc @sunng87

fix: Arc<T> impl Send and Sync does not require static bound for T

---

src/api/stmt.rs

fix: allow unknown type for Parse

---

src/api/portal.rs
src/messages/copy.rs
src/messages/data.rs
src/messages/extendedquery.rs
src/messages/response.rs
src/messages/startup.rs
src/messages/terminate.rs

This patch add `#[non_exhaustive]` attribute to all of our types that provides pub access of its members. 
This is the followup of #144

refactor: make all pub type non_exhaustive

---

examples/duckdb.rs
examples/sqlite.rs
src/api/query.rs
src/api/results.rs
tests-integration/test-server/src/main.rs

This patch refactors `do_describe` in `ExtendedQueryHandler` to avoid misunderstanding of different data requirement for describing statement or portal. 
It split `do_describe` into `do_describe_statement` and `do_describe_portal`, and uses accurate return type for each.

refactor: use separated callback and return type for describe

---

examples/bench.rs
src/api/results.rs

The patch further optimises `DataRowEncoder` that removes `field_buffer`.
The performance is on-par with previous implementation for small data fields. But for larger text fields, we saw a small improvement.

refactor: reduce bytes copy and allocation of field_buffer

---

src/messages/mod.rs
src/messages/startup.rs

```rust
let mut bytes = BytesMut::new();
PgWireBackendMessage::Authentication(Authentication::SASLFinal(Bytes::from("Hello")))
.encode(&mut bytes);
// Panic !!!
PgWireBackendMessage::decode(&mut bytes);
```
```
thread 'main' panicked at /Users/.../bytes-1.6.0/src/bytes_mut.rs:386:9:
split_to out of bounds: 9 <= 5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Fix SASL body decode

---

.github/workflows/ci.yml
.gitignore
Cargo.toml
src/error.rs
src/lib.rs
src/messages/data.rs
src/messages/extendedquery.rs
tests-integration/rust-client/src/main.rs

This PR split the "server" into the `api feature`, which can significantly reduce the compilation time for those who just want to use the `messages` to write a Postgres client.
```toml
pgwire = "..."
pgwire = { version = "...", default-features = false }
```
```toml
log = "0.4"
time = "0.3"
```
This helps the client determine the value format
```diff
- pub(crate) const FORMAT_CODE_TEXT: i16 = 0;
+ pub const FORMAT_CODE_TEXT: i16 = 0;
```

Split api feature

---

.github/workflows/ci.yml
Cargo.toml
src/lib.rs

This is a follow-up for #177 
And it seems we should rename the `api` module to `server-api` as well. But to avoid bringing breaking change ahead of time, I'm going to do it when there is actual client api.

chore: rename api feature to server-api

---

Cargo.toml
src/api/auth/scram.rs

rustls 0.23 changed the default crypto provider from ring to aws-lc-rs
Allow feature selection to direct pgwire on which backend to prefer,
thankfully the use of ring has the exact same api in aws-lc-rs

Add 2 features: ring & aws-lc-rs

---

.github/workflows/ci.yml
Cargo.toml
README.md
src/api/auth/mod.rs
tests-integration/test-server/Cargo.toml

This patch makes scram an optional feature completely as it introduces a few cypto libraries you might not want if you do not use scram in your application.
cc @serprex , this changes some behaviour introduced in #179

feat: make scram an optional feature

---

examples/scram.rs
src/api/auth/scram.rs

This has two benefits:
1. takes 1 lock instead of 18
2. generates multiple bytes per internal random invocation

scram: generate random nonce with one call

---

examples/bench.rs
examples/duckdb.rs
examples/gluesql.rs
examples/scram.rs
examples/secure_server.rs
examples/server.rs
examples/sqlite.rs
src/api/auth/md5pass.rs
src/api/auth/scram.rs
src/api/mod.rs
src/tokio.rs
tests-integration/test-server/src/main.rs

As we have more and more handlers, startup, simple query, extended query and now copy, with logical replication may come soon, the `process_socket` api may need to accept a lot of arguments and break every time we introduce a new handler.
This patch sunsets our previous `MakeHandler` api and updated it to the new factory based api for both:
1. include all handler types in the API
2. take a responsibility of `MakeHandler` to control whether all not to create a new handler on new connections.

refactor: introducing handler factory

---

Cargo.toml
src/types/mod.rs

The `rust_decimal` crate provides a `Decimal` type that implements the `ToSQL` trait required for integration with `rust-postgres`.
This is one of the recommended ways[^1] of exposing `NUMERIC` and `DECIMAL` columns in `rust-postgres` / `tokio-postgres` results.
This commit introduces `rust_decimal` as an optional dependency and adds a `ToSqlText` implementation (similar to how the `chrono` types are pulled in and used to provide support for `DATE`/`TIME`/`DATETIME` Postgres types).
[^1]: https://stackoverflow.com/a/72626605

feat: implement `ToSqlText` for `Decimal`

---

examples/copy.rs
src/api/copy.rs
src/api/mod.rs
src/api/query.rs
src/tokio.rs

The recently introduced `CopyInProgress` state would be usually set by the code that handles a `COPY <t> FROM STDIN` statement.
The `process_message` loop should respect this behavior and only act on `CopyData` / `CopyDone` / `CopyFail` messages in this state.
In addition, the default `SimpleQueryHandler::on_query` implementation should no transition back to a `ReadyForQuery` state or send a response to the client if the `do_query` method ended with initiating a `COPY` phase.

feat: respect `CopyInProgress` state

---

examples/secure_server.rs
src/tokio.rs
tests-integration/rust-client/Cargo.toml
tests-integration/rust-client/src/main.rs
tests-integration/test-server/Cargo.toml
tests-integration/test-server/src/main.rs

Fixes #188 
To adopt postgres/libpq 17's new direct ssl feature, we add a new check for TLS first byte `0x16`. If matches, we go directly to ssl handshake process without SslRequest/SslResponse.

feat: add support for direct ssl

---

src/messages/startup.rs

There is no length checking in [decode_body](https://github.com/sunng87/pgwire/blob/master/src/messages/startup.rs#L197-L198) of `Authentication`, it will cause error when `buf` is larger than actual message.

Fix authentication message decode

---

src/messages/data.rs
src/messages/extendedquery.rs
src/messages/mod.rs

According to the PostgreSQL documentation, the upper limit for query parameters is 65,535, that cannot be represented as i16. (https://www.postgresql.org/docs/16/limits.html)
The old implementation caused a panic for parse and bind messages with more than 32,767 parameters. For instance, 65,535 turned into -1, which when cast to usize resulted in usize::MAX. This led to a panic during the allocation of a vector for usize::MAX parameters.

fix: use u16 type for parameters len

---

.github/workflows/ci.yml
Cargo.toml

This patch feature gated the duckdb example to speedup our test build

chore: skip building duckdb

---

src/types/mod.rs

We need to serialize array element with its item type instead of array type itself.

fix: array type text serialization

---

tests-integration/go/client.go
tests-integration/go/go.mod
tests-integration/go/go.sum
tests-integration/test.sh

Fixes https://github.com/sunng87/pgwire/issues/60
Writing an integration test to evaluate how the Go lib/pq client handles pgwire.

integration test for go(#60)

---

src/api/mod.rs
src/tokio.rs

We just have too much Arc wrappers required for `process_socket` and in some case it's totally not necessary. This change removes requirement for `Arc` and make it optional only when you are using a stateless handler.

refactor: do not require Arc for handler factory

---

src/tokio.rs

This fixes an issue that when client disconnected before sending any bytes, the server goes into a dead loop.
This issue was introduced in #189

fix: check peek return value of dead stream

---

src/api/mod.rs
src/messages/mod.rs
src/tokio.rs

Our previous implementation of peeking first packet can result in busy loop when insufficient bytes sent to server. This is because `peek` will return immediately when it has bytes available.

fix: avoid busy loop on insufficient bytes on connection

---

src/api/results.rs

At least with the `psql` client, execution command strings without `oid` print a notice: `could not interpret result from server: <string>`.
This PR changes the serialization of `Tag` to `CommandComplete` by adding `oid` between the tag and `rows`.
The case of `Some(oid)` and `None` `rows` is not covered, because it would serialize in an ambiguous way. This means that `oid` will be ignored if `rows` is `None`.

fix: command tag oid now shows up in string

---

.github/workflows/ci.yml
Cargo.toml
README.md
examples/bench.rs
examples/copy.rs
examples/gluesql.rs
examples/secure_server.rs
examples/server.rs
examples/transaction.rs
src/api/auth/cleartext.rs
src/api/auth/md5pass.rs
src/api/auth/mod.rs
src/api/auth/noop.rs
src/api/auth/scram.rs
src/api/mod.rs
src/api/query.rs
src/api/results.rs
src/api/transaction.rs
src/error.rs
src/tokio.rs

Fixes #170 
This patch adds transaction state tracking and allows developer to return transaction state change from `Response` type.
I also refactored `finish_authentication` in `pgwire::api::auth` to remove an `unwrap` usage.
Also set MSRV to 1.74 to fix a Sync marker issue

feat: track transaction state

---

.github/workflows/ci.yml
Cargo.toml
src/api/auth/scram.rs
src/tokio/server.rs

For those who don't want to include tls libraries, we provide a feature configuration `--no-default-features --features server-api` to exclude rustls library family.

refactor: make tls an optional feature

---

src/messages/extendedquery.rs

currently when try encode parse message it return incorrect message length because miss to count Int16 len of type_oids array
for example for `SELECT 7`, we got next body:
[80, 0, 0, 0, 16, 115, 48, 0, 83, 69, 76, 69, 67, 84, 32, 55, 0, 0, 0]
but expected:
[80, 0, 0, 0, 18, 115, 48, 0, 83, 69, 76, 69, 67, 84, 32, 55, 0, 0, 0]

fix parse message encode

---

examples/bench.rs
examples/copy.rs
examples/duckdb.rs
examples/gluesql.rs
examples/scram.rs
examples/secure_server.rs
examples/server.rs
examples/sqlite.rs
examples/transaction.rs
src/api/mod.rs
src/tokio/server.rs
tests-integration/test-server/src/main.rs

Our handler system lacks a centralized error processing mechanism. The errors produced by query handlers are dumped directly to upstream. There is no way for logging, error filtering, etc. This patch includes a new error handler allows you to track all errors generated from various handlers. By accept a mutable reference to the `PgWireError`, you are also modify it before sending to end user.

feat: add ErrorHandler for error processing

---

examples/scram.rs
examples/secure_server.rs
src/tokio/mod.rs
src/tokio/server.rs
tests-integration/test-server/src/main.rs

reexport tokio_rustls since TlsAcceptor type must come from same version
breaking change: when tls not enabled still require None to be passed,
thus code written without tls feature won't be broken when tls enabled

tls feature improvements

---

src/error.rs
src/tokio/server.rs

Fixes #238 
This patch changes how errors are processed for server. We will generate `ErrorInfo` for each variant of `PgWireError`, specify the error severity and code. For fatal errors, we will disconnect the client.

feat: improve error code and message generation

---

Cargo.toml
src/api/mod.rs
src/tokio/server.rs

This patch adds `ClientInfo` API access to the client certificate. This allows user to do mTLS in their `StartupHandler` implementation.

feat: add API access to client certificates

---

examples/bench.rs
examples/copy.rs
examples/duckdb.rs
examples/gluesql.rs
examples/scram.rs
examples/secure_server.rs
examples/server.rs
examples/sqlite.rs
examples/transaction.rs
src/api/query.rs
tests-integration/test-server/src/main.rs

Simplify and correct lifetime for do_query methods in query handlers. The Response lifetime doesn't have to be same with the query string.

fix: correct lifetime for do query

---

src/api/query.rs
src/api/stmt.rs

Adds ClientInfo to the parse_sql so that database, user name, etc is accessible.

Clientinfo parse_sql

---

src/api/auth/mod.rs
src/api/mod.rs
src/tokio/server.rs

this is the part one of query termination support. 
Previously the backend key part of this library is unusable. This patch allows user to generate and set unique pid and secret key for query termination.

feat: user visible backend keys

---

examples/bench.rs
examples/common/mod.rs
examples/copy.rs
examples/duckdb.rs
examples/gluesql.rs
examples/scram.rs
examples/secure_server.rs
examples/server.rs
examples/sqlite.rs
examples/transaction.rs
src/api/auth/noop.rs
src/api/cancel.rs
src/api/copy.rs
src/api/mod.rs
src/api/query.rs
tests-integration/test-server/src/main.rs

This patch is a breaking change but it's aimed to simplify the implementation of `PgWireServerHandlers` quite a bit. The new function signature uses `impl trait` style return value, and removed type definitions associated with the trait.
This allows us to set NoopHandler as default type and API won't break when we introduce new handlers.

refactor!: change PgWireServerHandlers to use impl trait return value

---

examples/common/mod.rs
src/api/auth/cleartext.rs
src/api/auth/md5pass.rs
src/api/auth/mod.rs
src/api/auth/noop.rs
src/api/auth/scram.rs
src/api/mod.rs
src/messages/mod.rs
src/messages/startup.rs

In this patch I removed `UNKNOWN` from `ProtocolVersion`. There won't be a unknown state. The server will always use `3.2` protocol version be default, and if client requests an alternative version the server knows about, it will downgrade to it. Otherwise, the server will start its protocol negotiation process hoping the client to know about it. This will be implemented in next patch.

feat: use protocol 3.2 by default, and downgrade to 3.0 if client requests

---

.gitignore
flake.nix
src/error.rs
src/messages/cancel.rs
src/messages/mod.rs
src/messages/startup.rs
src/tokio/client.rs
src/tokio/server.rs

Previously, due to lack of connection state context, we are unable to fully decode Frontend messages in one decode function. Thanks to `DecodeContext` introduced in recent commits, it's now possible to provide state information and we can fully capable.

refactor: add support for PgWireFrontMessage to decode special messages

---

src/tokio/server.rs

This adds support for "GSSMODE=prefer SSLMODE=require" 
Currently this fails but it should actually fallback to ssl mode since gss is preferred
```
psql "host=127.0.0.1 port=5433 user=myuser gssencmode=prefer sslmode=require dbname=postgres"
psql: error: connection to server at "127.0.0.1", port 5433 failed: server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.
```
This PR adds a loop to check required modes so that it falls back to when gss is not available ssl mode. 
```
psql "host=127.0.0.1 port=5433 user=myuser gssencmode=prefer sslmode=require dbname=postgres"
psql (14.18 (Homebrew), server 16.6-pgwire-0.31.1)
WARNING: psql major version 14, server major version 16.
Some psql features might not work.
SSL …
```

Support for GSSENCMODE=prefer SSLMODE=require - falling back to ssl mode

---

README.md
src/error.rs
src/messages/mod.rs
src/messages/response.rs
src/messages/startup.rs
src/tokio/server.rs

This patch adds support for GssEncRequest message codec and handshake support.
However, since we won't support GSSAPI encryption for now, the server will always reject handshake.

feat: GssEncRequest handshake

---

src/error.rs
src/messages/cancel.rs
src/messages/copy.rs
src/messages/data.rs
src/messages/extendedquery.rs
src/messages/mod.rs
src/messages/response.rs
src/messages/simplequery.rs
src/messages/startup.rs

This patch adds a limit of packet length according to postgres' own implementation:
- small frontend message is no larger than 10_000
- large frontend message has a limit of 0x3fffffff - 1
- small backend message is no larger than 30_000
- large backend message has no size limit

feat: packet length check

---

src/tokio/server.rs

We just hit [this issue](https://github.com/tokio-rs/tokio/issues/3789) with peeking SSL or GSS handshake packets. This patch updates the implementation to use a `BufStream` to buffer underlying bytes so we can use the buffer for peeking data.

fix: peek after read on windows

---

src/tokio/server.rs

It's not critical to use bufstream for tls, but in order to keep code consistent I just made the switch

fix: use bufstream for tls

---

.github/workflows/ci.yml
Cargo.toml
examples/duckdb.rs
examples/scram.rs
examples/sqlite.rs
src/api/auth/mod.rs
src/api/auth/sasl.rs
src/api/auth/sasl/scram.rs
src/api/auth/scram.rs
src/error.rs
src/messages/startup.rs
tests-integration/test-server/Cargo.toml
tests-integration/test-server/src/main.rs

This is a refactor step before we can have #298 in our SASL framework.
- decoupled concept of SASL and scram: SASL is an authentication framework, renamed `SASLScramAuthStartupHandler` to `SASLAuthStartupHandler`
- made scram enabled with ring or aws-lc-rs presents
- add `Sync` marker to `client` in `StartupHandler`
- removed panic behaviour for `PasswordMessageFamily`

refactor: remove scram feature gate, discouple sasl and scram concept

---

examples/bench.rs
examples/common/mod.rs
examples/duckdb.rs
examples/gluesql.rs
examples/sqlite.rs
examples/transaction.rs
src/api/results.rs

Call `Box::pin` in `QueryReponse::new` so user won't need to call it.
Partially in #305

refactor: accept generic stream in QueryResponse::new

---

src/api/mod.rs
src/api/portal.rs
src/api/query.rs
src/api/results.rs
src/api/store.rs
src/tokio/server.rs

This patch removes `PortalSuspendedResults` introduced in #303 and use portal itself to hold a state for it. It keeps tracking portal state with: 
- `Initial`: unexecuted portal
- `Suspended`: portal partially fetched
- `Finished`: portal completely fetched
This also removes mutex from the stream in `QueryResponse`. The stream will be moved accordingly as execution state advances.
Partially for #305 
@xhwhis

refactor: store unfinished data stream in portal

---

Cargo.toml
src/api/client/result.rs
src/api/results.rs
src/types/from_sql_text.rs
src/types/to_sql_text.rs

Fixes #320 
This patch introduces ToSqlText/FromSqlText for serde types and serde_json::Value.
This patch also reorganized features for various extension types. Extension types will be disabled when you include pgwire with `no-default-features`

feat: from/to sql text for json/serde types
